// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P1_AP1_YudelkaTorres.DAL;

#nullable disable

namespace P1_AP1_YudelkaTorres.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20251011050739_Detalle")]
    partial class Detalle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("P1_AP1_YudelkaTorres.Models.EntradasHuacales", b =>
                {
                    b.Property<int>("EntradaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EntradaId");

                    b.ToTable("EntradasHuacales");
                });

            modelBuilder.Entity("P1_AP1_YudelkaTorres.Models.EntradasHuacalesDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntradaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetalleId");

                    b.HasIndex("EntradaId");

                    b.HasIndex("TipoId");

                    b.ToTable("EntradasHuacalesDetalle");
                });

            modelBuilder.Entity("P1_AP1_YudelkaTorres.Models.EntradasHuacalesTipos", b =>
                {
                    b.Property<int>("TipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripción")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.HasKey("TipoId");

                    b.ToTable("EntradasHuacalesTipos");

                    b.HasData(
                        new
                        {
                            TipoId = 1,
                            Descripción = "Huacal Verde",
                            Existencia = 4
                        },
                        new
                        {
                            TipoId = 2,
                            Descripción = "Huacal Rojo",
                            Existencia = 5
                        },
                        new
                        {
                            TipoId = 3,
                            Descripción = "Huacal Azul",
                            Existencia = 3
                        },
                        new
                        {
                            TipoId = 4,
                            Descripción = "Huacal Amarrillo",
                            Existencia = 6
                        },
                        new
                        {
                            TipoId = 5,
                            Descripción = "Huacal Negro",
                            Existencia = 2
                        });
                });

            modelBuilder.Entity("P1_AP1_YudelkaTorres.Models.EntradasHuacalesDetalle", b =>
                {
                    b.HasOne("P1_AP1_YudelkaTorres.Models.EntradasHuacales", "EntradaHuacal")
                        .WithMany("EntradasHuacalesDetalle")
                        .HasForeignKey("EntradaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P1_AP1_YudelkaTorres.Models.EntradasHuacalesTipos", "EntradaHuacalTipo")
                        .WithMany("EntradasHuacalesDetalle")
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntradaHuacal");

                    b.Navigation("EntradaHuacalTipo");
                });

            modelBuilder.Entity("P1_AP1_YudelkaTorres.Models.EntradasHuacales", b =>
                {
                    b.Navigation("EntradasHuacalesDetalle");
                });

            modelBuilder.Entity("P1_AP1_YudelkaTorres.Models.EntradasHuacalesTipos", b =>
                {
                    b.Navigation("EntradasHuacalesDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
